name: Upload Python Package

on:
  release:
    - created

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get tag and version
      id: util
      run: echo "::set-output name=version::${GITHUB_REF:11}"

    - name: Edit setup.py for new release
      env:
        VERSION: ${{ steps.util.outputs.version }}
        DOWNLOAD_URL: https://github.com/${{ github.repo }}/archive/v${{ steps.util.outputs.version }}.tar.gz
      run: envsubst < .github/setup.py.tmpl > setup.py

    - name: Output setup.py
      run: cat setup.py

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install setuptools wheel twine

    # - name: Build and publish
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     python setup.py sdist bdist_wheel
    #     twine upload dist/*
